### ISSUE TITLE
etcd-metrics-server panics if it can't connect to nats

### ISSUE THREAD

**Issue by combor** [cloudfoundry-incubator/etcd-metrics-server#4]
If `etcd-metrics-server` has wrong password to nats it panics with 
```
panic: close of closed channel

goroutine 21 [running]:
github.com/cloudfoundry/gunk/diegonats.func·002(0xc20805e400)
        /var/vcap/packages/etcd_metrics_server/src/github.com/cloudfoundry-incubator/etcd-metrics-server/Godeps/_workspace/src/github.com/cloudfoundry/gunk/diegonats/nats_client.go:
39 +0x2a
github.com/apcera/nats.(*Conn).close(0xc20805e400, 0x2, 0xc20802ac01)
```
This is a golang bug that was fixed here: https://github.com/golang/go/commit/b016eba489820b9091e4f39610a84f697d8eb0f9 and was released in go 1.5. It seems that `etcd-metrics-server` is still compiled with 1.4.3 so it's still vulnerable.

**Comment by Amit-PivotalLabs** [comment]
Hey @combor 

Sorry for the delayed response.  We're going to bump a few things we maintain to go1.6: https://www.pivotaltracker.com/story/show/116174561

We will then be able to come back and close out this issue for you.

Cheers,
Amit

**Comment by ryanmoran** [comment]
This issue should be resolved by https://github.com/cloudfoundry-incubator/etcd-release/commit/accd04c10d7bfb5f438ece18df956cec4e333125
